### ISSUE TITLE
Unable to add repo in HACS

### ISSUE THREAD

**Issue by Sloth-on-meth** [Lawris/Plassonade-s-Dashbaord#1]
I'm doing something wrong maybe - i cannot add this repositie

**Comment by Lawris** [comment]
Hey, this repo shouldn't be added as a custom component on HACS. This repository is just the source code of my own dashboard, made with other HACS components that I list in the README.
If you have any issue with the implementation, [feel free to join our discord here](https://plassonade.com/links) and get help from our community :)
