### ISSUE TITLE
Roomcard

### ISSUE THREAD

**Issue by 0xvisualiris** [Lawris/Plassonade-s-Dashbaord#2]
Hey there,
I love your work in the room card and trying to implement this however in my homeassistant dashboard. Love the idea with the chips card on the card. But my problem is, that the chips card is stuck in the top right corner of the tile.

Do you have an idea why?

![Bildschirmfoto 2024-09-03 um 09 49 22](https://github.com/user-attachments/assets/6ab922b8-bb90-4872-b16f-813730b8478c)

`type: custom:stack-in-card
keep:
  margin: false
  box_shadow: false
  background: false
mode: horizontal
card_mod:
  style: |
    ha-card {
      border: none;
    }
cards:
  - type: custom:mushroom-template-card
    primary: Badezimmer
    secondary: '{{states("sensor.bewegungssensor_badezimmer_temperatur")}} °C'
    icon: mdi:bathtub
    entity: light.badezimmer_deckenlampe
    icon_color: '{{ state_attr(entity, "rgb_color")}}'
    badge_icon: >
      {% if is_state('binary_sensor.bewegungssensor_badezimmer_bewegung', 'on')
      %}
        mdi:motion-sensor
      {% else %}
        mdi:none
      {% endif %}
    badge_color: >
      {% if is_state('binary_sensor.bewegungssensor_badezimmer_bewegung', 'on')
      %}
        green
      {% else %}
        mdi:none
      {% endif %}
    fill_container: true
    card_mod:
      style: |
        ha-card {
          border: none;
          width: 170%
        }
  - type: custom:mushroom-chips-card
    chips:
      - type: action
        icon: mdi:arrow-right
        style: |
          ha-card {
            border: none;
          }
    alignment: end
    style: |
      ha-card {
        display: flex;
        align-items: center;
        justify-content: right;
        height: 100%;
        border: full;
        padding-right: 8px;
        --chip-spacing: 0px;
        #--chip-border: none;
        --chip-background: transparent;
      }
`

**Comment by RapierXbox** [comment]
Download Card Mod from HACS and add `card_mod: ` before `style: |` or just look at my pull request
![image](https://github.com/user-attachments/assets/e406bdd6-2bf6-456c-b977-c272681f7ba3)

**Comment by 0xvisualiris** [comment]
I can't get it to work. I already installed Card-Mod for sure. 
But something is not working for me. 

`
square: false
type: grid
cards:
  - type: custom:stack-in-card
    keep:
      margin: false
      box_shadow: false
      background: false
    mode: horizontal
    card_mod:
      style: |
        ha-card {
          border: none;
        }
    cards:
      - type: custom:mushroom-template-card
        primary: Badezimmer
        secondary: '{{ states("sensor.bewegungssensor_badezimmer_temperatur") }} °C'
        icon: mdi:bathtub
        entity: light.badezimmer_deckenlampe
        icon_color: '{{ state_attr(entity, "rgb_color") }}'
        badge_icon: >
          {% if is_state('binary_sensor.bewegungssensor_badezimmer_bewegung',
          'on') %}
            mdi:motion-sensor
          {% else %}
            mdi:none
          {% endif %}
        badge_color: >
          {% if is_state('binary_sensor.bewegungssensor_badezimmer_bewegung',
          'on') %}
            green
          {% else %}
            mdi:none
          {% endif %}
        fill_container: true
        card_mod:
          style: |
            ha-card {
              border: none;
              width: 170%;
            }
      - type: custom:mushroom-chips-card
        chips:
          - type: action
            icon: mdi:arrow-right
            style: |
              ha-card {
                border: none;
              }
        alignment: end
        style: |
          ha-card {
            display: flex;
            align-items: center;
            justify-content: flex-end;
            height: 100%;
            border: none;
            padding-right: 14px;
            --chip-spacing: 0px;
            --chip-background: transparent;
          }
  - type: custom:stack-in-card
    keep:
      margin: false
      box_shadow: false
      background: false
    mode: horizontal
    card_mod:
      style: |
        ha-card {
          border: none;
        }
`
        
I also restarted HomeAssistant more then one time. 
![Bildschirmfoto 2024-09-03 um 13 58 21](https://github.com/user-attachments/assets/64b29eb9-4101-4e76-87bd-cfc63f92c169)


I installed card-mod with HACS. And I see that there is the Ressource 


Any idea?

**Comment by RapierXbox** [comment]
Ok so first go  to your dashboard and add a new custom yaml card  then paste this code. this is mine but make sure you modify the entitys to   use the ones that you have:
 ```
type: custom:stack-in-card
keep:
  margin: false
  box_shadow: false
  background: false
mode: horizontal
card_mod:
  style: |
    ha-card {
      border: none;
    }
cards:
  - type: custom:mushroom-template-card
    primary: Esszimmer
    secondary: '{{states("sensor.temperature_shelly_wohnzimmer")}} °C'
    icon: mdi:table-chair
    icon_color: |
      {% if is_state(entity, 'on') %}
        yellow
      {% else %}
        gray
      {% endif %}
    entity: switch.relay_shelly_wohnzimmer
    fill_container: true
    card_mod:
      style: |
        ha-card {
          border: none;
          width: 170%
        }
    tap_action:
      action: toggle
  - type: custom:mushroom-chips-card
    chips:
      - type: action
        icon: mdi:arrow-right
        style: |
          :host {
            --chip-spacing: 0px;
            --chip-background: transparent;
            border: none;
          }
        tap_action:
          action: navigate
          navigation_path: /lovelace/esszimmer
    alignment: end
    card_mod:
      style: |
        ha-card {
          display: flex;
          align-items: center;
          justify-content: flex-end;
          height: 100%;
          padding-right: 14px;
        }
```

**Comment by 0xvisualiris** [comment]
> Ok so first go to your dashboard and add a new custom yaml card then paste this code. this is mine but make sure you modify the entitys to use the ones that you have:
> 
> ```
> type: custom:stack-in-card
> keep:
>  margin: false
>  box_shadow: false
>  background: false
> mode: horizontal
> card_mod:
>  style: |
>    ha-card {
>      border: none;
>    }
> cards:
>  - type: custom:mushroom-template-card
>    primary: Esszimmer
>    secondary: '{{states("sensor.temperature_shelly_wohnzimmer")}} °C'
>    icon: mdi:table-chair
>    icon_color: |
>      {% if is_state(entity, 'on') %}
>        yellow
>      {% else %}
>        gray
>      {% endif %}
>    entity: switch.relay_shelly_wohnzimmer
>    fill_container: true
>    card_mod:
>      style: |
>        ha-card {
>          border: none;
>          width: 170%
>        }
>    tap_action:
>      action: toggle
>  - type: custom:mushroom-chips-card
>    chips:
>      - type: action
>        icon: mdi:arrow-right
>        style: |
>          :host {
>            --chip-spacing: 0px;
>            --chip-background: transparent;
>            border: none;
>          }
>        tap_action:
>          action: navigate
>          navigation_path: /lovelace/esszimmer
>    alignment: end
>    card_mod:
>      style: |
>        ha-card {
>          display: flex;
>          align-items: center;
>          justify-content: flex-end;
>          height: 100%;
>          padding-right: 14px;
>        }
> ```

Thanks! Pretty close. Now I have only a border outline or something around the mushroom chips card

**Comment by RapierXbox** [comment]
Oh sorry I forgot the css for the transperent background... replace the last ha-card with this:  
```
ha-card {
          display: flex;
          align-items: center;
          justify-content: flex-end;
          height: 100%;
          padding-right: 14px;
          --chip-spacing: 0px;
          --chip-border: none;
          --chip-background: transparent;
        }
```

**Comment by 0xvisualiris** [comment]
> Oh sorry I forgot the css for the transperent background... replace the last ha-card with this:
> 
> ```
> ha-card {
>           display: flex;
>           align-items: center;
>           justify-content: flex-end;
>           height: 100%;
>           padding-right: 14px;
>           --chip-spacing: 0px;
>           --chip-border: none;
>           --chip-background: transparent;
>         }
> ```

Thanks for the edit. But funny thing is, that it's not working. Maybe there is an error in my "Test Dashboard" or something else. Need to look into that.

But you helped me alot mate! Thanks! :)

**Comment by Lawris** [comment]
Thank you guys for your inputs. @RapierXbox made me realized that I forgot to add card_mod as a prerequisite! 😄 
I think we can close this issue.

**Comment by 0xvisualiris** [comment]
I got it to work... I created this nobordertheme.yaml

rounded_theme:
  # Kachel-Spezifikationen (rund und ohne Schatten)
  ha-card-box-shadow: "none"   # Entfernt den Schatten der Karten
  ha-card-border-radius: "10px"  # Runde Ecken (oder „50%“ für voll runde Karten)
  ha-card-border-width: "0px"   # Entfernt die Breite des Kartenrands

  # Transparenz und Schatten
  card-border-color: "transparent"  # Macht die Ränder vollständig transparent
  card-shadow: "none"  # Kein Schatten

  # Andere mögliche Anpassungen
  input-border-color: "transparent"  # Entfernt Ränder um Eingabefelder


And selected the theme in the dashboard :D
